- hosts: cateow
  become: yes
  become_user: root
  vars:
    project_directory: "/vagrant/cateow"
  tasks:
    - name: install {{ item }}
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - python
        - python-pip
    - name: install {{ item }}
      pip:
        name: "{{ item }}"
      with_items:
        - virtualenv
    - name: add environment variables
      lineinfile:
          dest: /home/vagrant/.bashrc
          line: "{{ item }}"
      with_items:
        - 'PROJDIR="{{ project_directory }}"'
        - 'cd "$PROJDIR"'
        - 'source "$PROJDIR/.venv/py/bin/activate"'
    - name: prepare env
      shell: "{{ item }}"
      with_items:
        - 'virtualenv {{ project_directory }}/.venv/py'
        - 'cd {{ project_directory }} ; .venv/py/bin/python setup.py develop'
